app:
  title: Konippi
  description: >
    Hi There! I'm a 1st Year Master's Student at the University in Kyoto, Japan. 
    I'm interested in Web Application Development.
    Do Stop by the Site If You're Interested in My Work!
